### ISSUE TITLE
Issue with Findall addin

### ISSUE THREAD

**Issue by chimera911** [giulianoriccio/Lua#11]
The findall add in will not pick up temp items, such as those from abyssea. Any way of making it notice them?

**Comment by giulianoriccio** [comment]
yes, it's possible. i didn't add them because i didn't think someone would actually use findall to look for them.
i will add the temp items in the next update.

**Comment by chimera911** [comment]
thanks... would appreciate it.

**Comment by giulianoriccio** [comment]
I've added it a few hours after the last time I replied to you.
It should be already working :)
