### ISSUE TITLE
Custom Timestamp Formats not recognized properly

### ISSUE THREAD

**Issue by dustin-lennon** [giulianoriccio/Lua#19]
When having a custom timestamp such as ${m}${day}|${hour12}:${min}${ampm} it shows up in chat as 06${day}|${hour12}:${min}${ampm}. It can be noticed in the screen shot attached to this post.

![ffxi_2013 06 06_21 57 13](https://f.cloud.github.com/assets/92093/621955/55ded310-cf20-11e2-92b6-fe257cb36aac.png)

**Comment by giulianoriccio** [comment]
It should be fixed.
Thank you for the report.
