### ISSUE TITLE
Findall Suggestion

### ISSUE THREAD

**Issue by ghost** [giulianoriccio/Lua#28]
Maybe a //findall -bags command that just reported how full your inventory was like..

Safe: 78/80 Locker: 22/80... Satchel: 80/80 Inventory: 71/80

**Comment by giulianoriccio** [comment]
I'll think about it, maybe it could also show the status of the mules.

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
