### ISSUE TITLE
Plasmon does not download correctly from launcher and shortcut command is incorrect

### ISSUE THREAD

**Issue by quedari** [giulianoriccio/Lua#3]
After repeatedly trying to download plasmon using the launcher and it not downloading anything but the plasmon folder (empty except for the "data" folder which was also empty), I finally downloaded it manually. Then I tried to execute commands with //delve test or //delve show, and it did nothing. So I tried //plasmon test and it worked perfectly. Just wanted to let you know.

**Comment by giulianoriccio** [comment]
The download issue depends on a bug found in the launcher. It has been fixed already but the update server had some issues and the players weren't able to download the fix. It should be ok by now.

About the "delve" command, thank you for letting me notice and sorry for the confusion, I've fixed the readme.
