### ISSUE TITLE
endurance 

### ISSUE THREAD

**Issue by Latravant** [giulianoriccio/Lua#31]
Endurance will not let me open the gate that leads to Temple of Uggalepih using the stone picture frame.  I click it, than it says, by focusing your thoughts on  the paintbrush of souls, a new painting begins to appear.... 

Then Endurance skips the line for me and doesnt give me time to wait on clicking the picture frame to open the gate.

**Comment by Latravant** [comment]
accidentally closed it.

**Comment by giulianoriccio** [comment]
Sorry for the late reply,
it's a known issue but at the moment there isn't a way to detect this kind of messages besides adding the specific NPC name to an exceptions list.

Do you happen to know if it has a specific name or is a blank target?

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
