### ISSUE TITLE
Reive Addon not working

### ISSUE THREAD

**Issue by ghost** [giulianoriccio/Lua#32]
I do not know what the exact issues is but it doesnt seem to start up proper or track exp/bayld.
Thank you.

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
