### ISSUE TITLE
Errors on /logout

### ISSUE THREAD

**Issue by Aerroenu** [giulianoriccio/Lua#33]
I've been getting a couple of errors everytime I /logout.

On the console, I'll get the message:
"You have to be logged in to use the addon."

Periodically, I'll get:
findAll: Lua error (runtime) = ...Windower4/addons/findall/findall.lua:(path gets cut off here)

I also get this error in the chat log, even after being logged on well after the initial loading time:
"findAll Error: findAll wasn't ready."

**Comment by IBHalliwell** [comment]
Hi,

I also have been seeing this message on and off, especially when quickly logging into my characters for the Repeat Login Campaign.  To avoid this I've been going through my various storage containers and doing a sort on them.

Thank you for a wonderful addon

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
