### ISSUE TITLE
Item changes name

### ISSUE THREAD

**Issue by Matoks** [giulianoriccio/Lua#34]
Hunter's socks in inventory are correctly shown by findall as hunter's socks.  When transferred to porter moogle as slip 4, they are shown as hunter's braccae.

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
