### ISSUE TITLE
Plasmon issue

### ISSUE THREAD

**Issue by ghost** [giulianoriccio/Lua#35]
When the delve first starts plasmon will show on screen, soon as you enter it however will disappear. Have to reload it but then it doesnt pick anything up til the first monster is killed and after delve it wont go away til you reload it again.
Any fix for this?
Thank you.

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
