### ISSUE TITLE
Suggestion:  Be able to get a list of everything

### ISSUE THREAD

**Issue by IBHalliwell** [giulianoriccio/Lua#36]
Hi,

One of the advantages of Find over Findall (which is what I'd like to move to exclusively) is being able to find out everything on a character.  Basically, if you enter just the "Find" command it gives you a list of every storage / inventory slot (even the temporary).

It is very useful because many times I don't know what I have on a mule or even on my man character.  Right now (as I understand it) with Findall one needs to know what to look for to create the query.

I'm not sure how the new syntax should look, but one should be able to list all the items help by:
(A) All characters
(B) One or more specific character(s)

Thank you,

I.B. Halliwell on Ragnarok (formerly Caitsith)

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
