### ISSUE TITLE
Item reported but not really there

### ISSUE THREAD

**Issue by IBHalliwell** [giulianoriccio/Lua#37]
I do the command:

findall whine

and the result says one of my characters has a "Whine Cellar Key" in the case, but the case is empty on the character.  This occurs EVEN WHEN LOGGED onto the character and issuing the command.

Just FYI:  The Find plugin reports the same.

I. B. Halliwell on Ragnarok (formerly of Caitsith)

**Comment by IBHalliwell** [comment]
Question:  is there a method to reset the find and/or findall database (the place where you're keeping the contents of each character)?  Even if this is manual (e.g. erasing one or more files) ....

**Comment by giulianoriccio** [comment]
Please report this here https://github.com/Windower/Lua/notifications

I'm not playing anymore so I cannot help you
