### ISSUE TITLE
Slip 14 spelling error

### ISSUE THREAD

**Issue by Schliematt** [giulianoriccio/Lua#38]
On slip 14 "Ares's Mask +1" is missing the "+1". Just noticed also its missin the "s" after the apostrophe, Thanks!

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
