### ISSUE TITLE
timestamp not displaying

### ISSUE THREAD

**Issue by demonreaper** [giulianoriccio/Lua#39]
Timestamp is not displaying its showing that its loaded but will not display time

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
