### ISSUE TITLE
Chars Addon - Missing chat.chars

### ISSUE THREAD

**Issue by ragingchaos** [giulianoriccio/Lua#40]
Chars is no longer outputting characters into outgoing text (ex: < note > turns up empty). Seems the file is referencing chat.chars, is this file missing?

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
