### ISSUE TITLE
findAll doesn't detect items in mog safe 2

### ISSUE THREAD

**Issue by xurion** [giulianoriccio/Lua#41]
Doing findall beast does not detect my beastmaster AF gear in mog safe 2. Simply extending the list of storages in the Lua file to include 'safe2' resulted in findall detecting the items in mog safe 2.

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
