### ISSUE TITLE
Plasmon thinks Sinister Reign is Delve

### ISSUE THREAD

**Issue by KazyEXE** [giulianoriccio/Lua#43]
It also doesn't detect when you leave.

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
