### ISSUE TITLE
Findall - command line tracking

### ISSUE THREAD

**Issue by MartelRagnarok** [giulianoriccio/Lua#44]
Is there any possibility of going back to(or just adding) a track command to findall?

Like with the find plugin, where a simple //track qa Fire Crystal would make a entry with the same name that tracked the amount of fire crystals.

While the xml method is functional, and good for permanent entries it's pretty inconvenient for quickly adding temporary tracking. 

I mostly use tracking for crafting. Before I could just run a script to add the materials for the synth, then use a short command to clear them out after. Now I have to open my xml list of mats, paste the mats into my settings file, and reload. And findall lags like hell on that reload. Repeat process on two characters crafting different items.

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
